sudo: required
services:
  - docker

before_install:
  - docker build -t nishantbhosale/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nishantbhosale/react-test npm run test

after_success:
  - docker build -t nishantbhosale/multi-client ./client
  - docker build -t nishantbhosale/multi-nginx ./nginx
  - docker build -t nishantbhosale/multi-server ./server
  - docker build -t nishantbhosale/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nishantbhosale/multi-client
  - docker push nishantbhosale/multi-nginx
  - docker push nishantbhosale/multi-server
  - docker push nishantbhosale/multi-worker
