sudo: required
services:
  - docker

before_install:
  - docker build -t nishantbhosale/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nishantbhosale/react-test npm run test

after_success:
  - docker build -t nishantbhosale3/multi-client ./client
  - docker build -t nishantbhosale3/multi-nginx ./nginx
  - docker build -t nishantbhosale3/multi-server ./server
  - docker build -t nishantbhosale3/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nishantbhosale3/multi-client
  - docker push nishantbhosale3/multi-nginx
  - docker push nishantbhosale3/multi-server
  - docker push nishantbhosale3/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-677413250510"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
